In [1]:
from sklearn.cluster import KMeans

In [2]:
from ghmm import *

In [3]:
import numpy as np

In [4]:
import pickle

In [5]:
grfKMeans = pickle.load( open( "grfKMeans.model", "rb" ) )

In [6]:
grfDataset = pickle.load( open( "grfDataset_walking", "rb"))

In [7]:
grfDataset.shape


(1898, 10)

In [8]:
grfKMeans.predict(grfDataset[1213:1213+20])

array([ 5, 22, 16,  2, 59, 10, 20, 20, 59,  4, 56, 43, 26, 57,  5, 54, 54,
        5, 16, 44], dtype=int32)

In [9]:
count = 0

In [10]:
i = 0

In [11]:
N = 20

In [12]:
l = 0

In [13]:
seqList = []

In [14]:
seqLengths = []

In [15]:
while True:
    block = grfDataset[i:i+N]
    seq = grfKMeans.predict(block)
    l = seq.size
    seqList.append(seq)
    
    count = count + 1
    if l != N:
        break
    i = i + N
    
        

In [16]:
len(seqList)

95

In [17]:
#seqList

# 123

In [18]:
npA = np.random.dirichlet((1, 2, 3, 4, 5),size=5)

In [19]:
npB = np.random.dirichlet((1,2,3,4,5,6,7,8,9,10,
                           11,12,13,14,15,16,17,18,19,20,
                           21,22,23,24,25,26,27,28,29,30,
                           31,32,33,34,35,36,37,38,39,40,
                           41,42,43,44,45,46,47,48,49,50,
                           51,52,53,54,55,56,57,58,59,60,
                           61,62,63,64),size=5)

In [20]:
npA.shape

(5, 5)

In [21]:
npB.shape

(5, 64)

In [22]:
A=npA.tolist()

In [23]:
B=npB.tolist()

In [24]:
Pi=[1.0/5] * 5

In [25]:
sigma = IntegerRange(0,64)

In [26]:
hmmModel = HMMFromMatrices(sigma, DiscreteDistribution(sigma), A, B, Pi)

In [27]:
trainSet = SequenceSet(sigma, seqList)

In [28]:
hmmModel.baumWelch(trainSet, 100)

In [29]:
#print hmmModel

In [30]:
testSeq=EmissionSequence(sigma, [ 5, 22, 16,  2, 59, 10, 20, 20, 59,  4, 56, 43, 26, 57,  5, 54, 54,
        5, 16, 44] )

In [31]:
print(hmmModel.viterbi(testSeq))

([4, 3, 4, 3, 1, 2, 2, 2, 2, 2, 0, 4, 3, 4, 3, 4, 4, 3, 4, 3], -54.08454709077997)


# 參考: 
http://ghmm.sourceforge.net/documentation.html



In [ ]:
#print(hmmModel)

In [ ]:
#import pickle

In [ ]:
#pickle.dump(hmmModel, open("ghmmModel_standing", "wb"))

In [ ]:
#help('ghmm')

In [ ]:
A1=hmmModel.asMatrices()[0]

In [ ]:
B1=hmmModel.asMatrices()[1]

In [ ]:
Pi1=hmmModel.asMatrices()[2]

In [ ]:
hmmModel1 = HMMFromMatrices(sigma, DiscreteDistribution(sigma), A1, B1, Pi1)

In [ ]:
print(hmmModel1.viterbi(testSeq))

In [ ]:
# backup HMM

In [ ]:
HMM_PARAMS=[sigma, A1, B1, Pi1]

In [ ]:
pickle.dump(HMM_PARAMS, open("tt0", "wb"))

In [ ]:
# restore HMM

In [ ]:
HMM_PARAMSL = pickle.load(open("tt0", "rb"))

In [ ]:
sigmaL=HMM_PARAMSL[0]

In [ ]:
AL=HMM_PARAMSL[1]

In [ ]:
BL=HMM_PARAMSL[2]

In [ ]:
PiL=HMM_PARAMSL[3]

In [ ]:
hmmModelL = HMMFromMatrices(sigmaL, DiscreteDistribution(sigmaL), AL, BL, PiL)

In [ ]:
print(hmmModelL.viterbi(testSeq)[1])

In [ ]:
print(hmmModelL.loglikelihoods(testSeq))

In [ ]:
def myGHMMDump(sigma_, hmmModel_, fileName_):
    A_=hmmModel_.asMatrices()[0]
    B_=hmmModel_.asMatrices()[1]
    Pi_=hmmModel_.asMatrices()[2]
    
    HMM_PARAMS_=[sigma_, A_, B_, Pi_]
    pickle.dump(HMM_PARAMS_, open(fileName_, "wb"))

In [ ]:
def myGHMMLoad(fileName_):
    HMM_PARAMS_ = pickle.load(open(fileName_, "rb"))
    sigma_=HMM_PARAMS_[0]
    A_=HMM_PARAMS_[1]
    B_=HMM_PARAMS_[2]
    Pi_=HMM_PARAMS_[3]
    
    hmmModel_ = HMMFromMatrices(sigma_, DiscreteDistribution(sigma_), A_, B_, Pi_)
    return [sigma_, hmmModel_]

In [32]:
B1 = np.array(hmmModel.asMatrices()[1])

In [33]:
B1

array([[  7.91449033e-028,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   1.57125270e-010,   8.66930264e-016,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   8.47880725e-008,   0.00000000e+000,
          1.79961719e-001,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   3.76900891e-026,   0.00000000e+000,
          0.00000000e+000,   4.81024386e-016,   1.24079423e-007,
          3.39505228e-001,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          5.61839387e-002,   4.35012609e-003,   0.00000000e+000,
          2.27199433e-015,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000,   2.22756637e-005,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   8.32276687e-066,   1.88960174e-018,
          0.00000000e+000

In [34]:
indices_lower = B1 < 1e-100

In [35]:
B1[indices_lower] = 1e-100

In [36]:
B1

array([[  7.91449033e-028,   1.00000000e-100,   1.00000000e-100,
          1.00000000e-100,   1.57125270e-010,   8.66930264e-016,
          1.00000000e-100,   1.00000000e-100,   1.00000000e-100,
          1.00000000e-100,   8.47880725e-008,   1.00000000e-100,
          1.79961719e-001,   1.00000000e-100,   1.00000000e-100,
          1.00000000e-100,   3.76900891e-026,   1.00000000e-100,
          1.00000000e-100,   4.81024386e-016,   1.24079423e-007,
          3.39505228e-001,   1.00000000e-100,   1.00000000e-100,
          1.00000000e-100,   1.00000000e-100,   1.00000000e-100,
          5.61839387e-002,   4.35012609e-003,   1.00000000e-100,
          2.27199433e-015,   1.00000000e-100,   1.00000000e-100,
          1.00000000e-100,   1.00000000e-100,   1.00000000e-100,
          1.00000000e-100,   1.00000000e-100,   2.22756637e-005,
          1.00000000e-100,   1.00000000e-100,   1.00000000e-100,
          1.00000000e-100,   8.32276687e-066,   1.88960174e-018,
          1.00000000e-100

In [43]:
hmmModel.getEmission(0)

[7.914490325143e-28,
 0.0,
 0.0,
 0.0,
 1.5712526968987283e-10,
 8.66930263699862e-16,
 0.0,
 0.0,
 0.0,
 0.0,
 8.478807248705549e-08,
 0.0,
 0.17996171938843286,
 0.0,
 0.0,
 0.0,
 3.7690089117192854e-26,
 0.0,
 0.0,
 4.810243856418726e-16,
 1.2407942261540335e-07,
 0.3395052281399347,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.05618393866773364,
 0.004350126092657012,
 0.0,
 2.271994329820561e-15,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.2275663731816544e-05,
 0.0,
 0.0,
 0.0,
 0.0,
 8.3227668711726e-66,
 1.889601743533293e-18,
 0.0,
 0.005892305340746103,
 5.189610965186592e-16,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 8.99215411666415e-14,
 0.07877761593558391,
 0.32845928441967964,
 2.0625001622944068e-21,
 0.0,
 0.001279423515490679,
 0.005567869377139445,
 0.0,
 0.0,
 4.434156067183124e-09]

In [44]:
B0=np.array(hmmModel.getEmission(0))

In [45]:
B0

array([  7.91449033e-28,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   1.57125270e-10,   8.66930264e-16,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   8.47880725e-08,   0.00000000e+00,
         1.79961719e-01,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   3.76900891e-26,   0.00000000e+00,
         0.00000000e+00,   4.81024386e-16,   1.24079423e-07,
         3.39505228e-01,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         5.61839387e-02,   4.35012609e-03,   0.00000000e+00,
         2.27199433e-15,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   2.22756637e-05,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   8.32276687e-66,   1.88960174e-18,
         0.00000000e+00,   5.89230534e-03,   5.18961097e-16,
         0.00000000e+00,

In [46]:
indices_lower = B0 < 1e-100

In [47]:
B0[indices_lower] = 1e-100

In [48]:
B0

array([  7.91449033e-028,   1.00000000e-100,   1.00000000e-100,
         1.00000000e-100,   1.57125270e-010,   8.66930264e-016,
         1.00000000e-100,   1.00000000e-100,   1.00000000e-100,
         1.00000000e-100,   8.47880725e-008,   1.00000000e-100,
         1.79961719e-001,   1.00000000e-100,   1.00000000e-100,
         1.00000000e-100,   3.76900891e-026,   1.00000000e-100,
         1.00000000e-100,   4.81024386e-016,   1.24079423e-007,
         3.39505228e-001,   1.00000000e-100,   1.00000000e-100,
         1.00000000e-100,   1.00000000e-100,   1.00000000e-100,
         5.61839387e-002,   4.35012609e-003,   1.00000000e-100,
         2.27199433e-015,   1.00000000e-100,   1.00000000e-100,
         1.00000000e-100,   1.00000000e-100,   1.00000000e-100,
         1.00000000e-100,   1.00000000e-100,   2.22756637e-005,
         1.00000000e-100,   1.00000000e-100,   1.00000000e-100,
         1.00000000e-100,   8.32276687e-066,   1.88960174e-018,
         1.00000000e-100,   5.89230534e-

In [49]:
hmmModel.setEmission(0, B0)

In [51]:
hmmModel.normalize()

In [52]:
hmmModel.getEmission(0)

[7.914490325142994e-28,
 9.999999999999994e-101,
 9.999999999999994e-101,
 9.999999999999994e-101,
 1.5712526968987272e-10,
 8.669302636998614e-16,
 9.999999999999994e-101,
 9.999999999999994e-101,
 9.999999999999994e-101,
 9.999999999999994e-101,
 8.478807248705543e-08,
 9.999999999999994e-101,
 0.17996171938843275,
 9.999999999999994e-101,
 9.999999999999994e-101,
 9.999999999999994e-101,
 3.769008911719283e-26,
 9.999999999999994e-101,
 9.999999999999994e-101,
 4.810243856418723e-16,
 1.2407942261540327e-07,
 0.3395052281399345,
 9.999999999999994e-101,
 9.999999999999994e-101,
 9.999999999999994e-101,
 9.999999999999994e-101,
 9.999999999999994e-101,
 0.05618393866773361,
 0.004350126092657009,
 9.999999999999994e-101,
 2.2719943298205595e-15,
 9.999999999999994e-101,
 9.999999999999994e-101,
 9.999999999999994e-101,
 9.999999999999994e-101,
 9.999999999999994e-101,
 9.999999999999994e-101,
 9.999999999999994e-101,
 2.227566373181653e-05,
 9.999999999999994e-101,
 9.999999999999994